version: "3"

services:
  web:
    image: web
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: posto
    volumes:
      - ".:/usr/src/app"
    ports:
      - 8001:8001
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.16.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - 5601:5601
